name: Game Bug Report
title: "[Bug] <Insert short issue description here>"
description: Something isn't working as expected within the game client/server.
labels:
  - bug game
assignees:
  - misleadingname
body:
  - type: markdown
    attributes:
      value: "### Please search for existing issues before submitting a new one!"
  - type: dropdown
    id: game-version
    attributes:
      label: Game Platform
      description: Select which version of the game the bug occurred in.
      options:
        - Hollowgate (Roblox Prototype)
        - STAGA (Standalone Game)
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Write a short summary of the bug.
      placeholder: e.g. "Inventory disappears after loading save."
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Explain how to reliably trigger the issue.
      placeholder: |-
        1. Launch the game
        2. Load save slot with X
        3. Open inventory
        4. Observe missing items
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Inventory should display all saved items.
  - type: textarea
    id: additional-media
    attributes:
      label: Additional Media or Files
      description: Screenshots, videos, crash dumps, or logs that help demonstrate the issue.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (irrelevant for Hollowgate.)
      description: Anything else we should know? System specs, OS, client version, etc.
      placeholder: |
        OS: Windows 11
        Specs: Ryzen 5600G, 16GB RAM, RTX 3060
        Game Version: v0.9.3-beta
