name: Feature Request
title: "[Feature] <Insert feature title here>"
description: Suggest something to be added, changed, or removed in the game.
labels:
  - enhancement game
body:
  - type: markdown
    attributes:
      value: "### Please search for existing feature requests before posting!"
  - type: textarea
    id: request-description
    attributes:
      label: Request Description
      description: Write a short summary of the feature or change you're suggesting.
      placeholder: I want the game to...
  - type: textarea
    id: request-defense
    attributes:
      label: Defend the Request
      description: How would this affect balance, gameplay, or fairness?
      placeholder: It would help because...
  - type: textarea
    id: additional-media
    attributes:
      label: Additional Media or Files
      description: Any mockups, diagrams, or examples that support the request.
