name: Net Bug Report
title: ""
description: Something isn't working as expected on STAGANet.
labels:
  - bug server
assignees: misleadingname
body:
  - type: markdown
    attributes:
     value: "### Please search for existing issues to check for duplicate issues!"
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Provide a short, clear summary of the backend/server bug.
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Include exact steps, curl/API calls, client actions, etc. that led to this issue.
      required: true
      value: |-
        1. ...
        2. ...
        3. ...
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened on the server's end?
      required: true
  - type: textarea
    id: observed-behavior
    attributes:
      label: Observed Behavior / Logs
      description: What actually happened, and what logs/errors did you observe?
      required: true
  - type: textarea
    id: related-data
    attributes:
      label: Related Media / Data
      description: Attach logs, traces, API responses, payloads, etc. that help clarify the bug.
  - type: textarea
    id: context-info
    attributes:
      label: Additional Context
      description: Anything else you think is important or useful for identifying the issue.
